### PR TITLE
Fix path for stylesheet enqueued in the classic editor

### LINKED ISSUE #59: Editor: Don't try to load non-existent file
There's a filter for `mce_css` which injects the stylesheet into the editor. But it still tries to load a minified file which no longer exists.

https://github.com/wearerequired/wp-team-list/blob/3.0.0/includes/Plugin.php#L537-L551

### PR DESCRIPTION
**Pull request by ocean90**
Fixes #59.

Adds RTL support too.

### CODE REVIEW

File: includes/Plugin.php [hunk 1]
```diff
@@ -543,9 +543,8 @@ public function get_user_role( WP_User $user, $field = 'display_name' ) {
 	public function filter_mce_css( $stylesheets ) {
 		$styles = explode( ',', $stylesheets );
 
-		// Use minified libraries if SCRIPT_DEBUG is turned off.
-		$suffix   = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min';
-		$styles[] = plugins_url( 'css/wp-team-list' . $suffix . '.css', plugin_dir_path( __FILE__ ) );
+		$style = is_rtl() ? 'assets/css/style-rtl.css' : 'assets/css/style.css';
```
Comment (grappler) [inline includes/Plugin.php]:
```suggestion
		$style    = is_rtl() ? 'assets/css/style-rtl.css' : 'assets/css/style.css';
```
